### ISSUE TITLE
Custome Filters 

### ISSUE THREAD

**Issue by rajatpathak** [wlanjie/trinity#47] opened 2020-07-31 13:48 UTC
How to create custom filters and all? Is there any editor? 

Please guide.

Thanks!

**Comment by ganeshappentus** [comment] 2020-08-01 05:48
@wlanjie

**Comment by wlanjie** [comment] 2020-08-01 10:19
No, need to adjust manually

**Comment by rocky8roy** [comment] 2020-08-01 10:28
is there support for launguages?

**Comment by rocky8roy** [comment] 2020-08-01 11:16
> No, need to adjust manually

can we use english in app

**Comment by wlanjie** [comment] 2020-08-01 12:55
no,this app is demo, you can using google translate

**Comment by rocky8roy** [comment] 2020-08-01 21:32
can you please explain usage of it like after implementation  'com.github.wlanjie:trinity:0.2.9.1' of this
how can we use it in our existing app in android studio
how it can be merged with java code of existing app

Or other way you can suggest like how we can use your sample code in our existing app code in android studio in java
android studio supports both java and kotlin both in same project.

**Comment by wlanjie** [comment] 2020-08-02 05:11
You can refer to the code in the app

**Comment by rocky8roy** [comment] 2020-08-02 20:14
i have implemented it and partially it is working also but when i tap on filters it crashes and gives below mentioned error :
E/CustomActivityOnCrash: The previous app process crashed. This is the stack trace of the crash:
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:448)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.abc.xyz/cache/filter/filter.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at java.io.FileInputStream.<init>(FileInputStream.java:103)
        at com.abc.xyz.adapter.FilterAdapter.<init>(FilterAdapter.kt:29)
        at com.abc.xyz.editor.LutFilterChooser.init(LutFilterChooser.kt:35)
        at com.abc.xyz.editor.Chooser.<init>(Chooser.kt:21)
        at com.abc.xyz.editor.LutFilterChooser.<init>(LutFilterChooser.kt:22)
        at com.abc.xyz.EditorActivity.setActiveIndex(EditorActivity.kt:261)
        at com.abc.xyz.EditorActivity.onTabSelected(EditorActivity.kt:241)
        at com.abc.xyz.view.TabLayout$1.onTabSelected(TabLayout.java:715)
        at com.abc.xyz.view.TabLayout.dispatchTabSelected(TabLayout.java:1681)
        at com.abc.xyz.view.TabLayout.selectTab(TabLayout.java:1674)
        at com.abc.xyz.view.TabLayout.selectTab(TabLayout.java:1634)
        at com.abc.xyz.view.TabLayout$Tab.select(TabLayout.java:1984)
        at com.abc.xyz.view.TabLayout$TabView.performClick(TabLayout.java:2142)
        at android.view.View$PerformClick.run(View.java:24774)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6533)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

filter and effect folder is not getting created

kindly help!

**Comment by wlanjie** [comment] 2020-08-03 02:19
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.abc.xyz/cache/filter/filter.json (No such file or directory) filter file is not exist

**Closed** 2020-09-25 10:53 UTC
